### ISSUE TITLE
Departamento precisa ser um model?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/apoio#3]
O model é um tipo de dado que escala. No caso de departamentos, temos 11, e são praticamente estáticos.  Se esse model se refere literalmente a esses departamentos , eu faria:
- pegar do replicado direto, ou
- um array hardcoded resolveria também 

Não é um problema em si ter o model,  mas se não vai escalar, talvez não valha a pena manter uma tabela no db com 11 linhas.

**Comment by ricardfo** [comment]
Embora o nome seja departamento eles cadastram os setores e centros também, como CITRAT, Tesouraria e STI. Talvez seja melhor mudar o nome da tabela.

**Comment by thiagogomesverissimo** [comment]
Entendi. Então beleza, é um tipo de departamento mais genérico.
